export {default as USDT} from "../assets/icons/cryptocurrency.svg";
export {default as BTC} from "../assets/icons/bitcoin.svg";
export {default as ETH} from "../assets/icons/eth.svg";
export {default as BNB} from "../assets/icons/bnb.svg";
export {default as Avatar} from "../assets/icons/avatar-icon-2.svg";
export {default as NOTFOUND} from "../assets/icons/notfound.svg";
export {default as Verified} from "../assets/icons/verified.svg";
export {default as Warning} from "../assets/icons/warning.svg";
export {default as NGN} from "../assets/icons/ngn.svg";
export {default as Checked} from "../assets/images/success-oyola.gif";
export {default as fileLock} from "../assets/icons/filelock.svg";
export {default as Upload} from "../assets/icons/upload.svg";
export {default as yellowWarning} from "../assets/icons/yellowarning.svg";
export {default as successicon} from "../assets/icons/successicon.svg";
// export {default as Redirect} from "../asset/icons/redirect.svg";
